Repository GEON-PPANG/GEON-PPANG-AOS, pull requests merged in 2023-08, with the labels that each got.

#68 [mod] 칩, 바텀 네비 디자인 수정
  app/src/main/res/drawable/background_bottom_navigation.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#71 [mod] 리스트 item 수정(빵집, 내 저장목록)
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/common/BakeryAdapter.kt
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#73 [mod] 검색뷰 디자인 수정
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchCountAdapter.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/layout_search_count.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫, 🔮mod 🔮

#77 [mod] 건빵집 리스트 디자인 수정
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/res/drawable/ic_bakery_list_filter.xml
  app/src/main/res/drawable/ic_filter_checked.xml
  app/src/main/res/drawable/ic_filter_unchecked.xml
  app/src/main/res/drawable/selector_my_filter_checked.xml
  app/src/main/res/layout/dialog_bottom_bakery_list_sort.xml
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/menu/bnv_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#81 [feat] 상세페이지 FAB 구현 + API 수정사항 반영 (홈, 상세페이지)
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBestBakery.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBestReview.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseDetailBakery.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseDetailReview.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BakeryInfo.kt
  app/src/main/java/com/sopt/geonppang/domain/model/ReviewData.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_detail_review_graph.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#86 [mod] 상세페이지 디자인 수정
  app/src/main/java/com/sopt/geonppang/domain/model/BakeryInfo.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/res/drawable/background_detail_review.xml
  app/src/main/res/drawable/background_detail_review_button.xml
  app/src/main/res/drawable/ic_bookmark_selected.xml
  app/src/main/res/drawable/ic_detail_logo_profile.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_smile.png
  app/src/main/res/drawable/ic_smile.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_detail_menu.xml
  app/src/main/res/layout/item_detail_review.xml
  app/src/main/res/layout/item_detail_review_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#83 [mod] 건빵집 리스트 api 수정
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/BakeryDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBakeryList.kt
  app/src/main/java/com/sopt/geonppang/data/repository/BakeryRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/BakeryService.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/BakeryRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/res/color/selector_bread_lost_filter_background.xml
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/item_bakery.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#90 [mod] 내 저장목록 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseMypageBookmark.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyBookMarksActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_station.xml
  app/src/main/res/layout/activity_my_bookmarks.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#93 [feat] 유저 필터 조회 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/GetUserFilterDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseGetUserFilter.kt
  app/src/main/java/com/sopt/geonppang/data/repository/GetUserFilterRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/FilterService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/UserFilter.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/GetUserFilterRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#95 [feat] 홈 뷰 말풍선 구현
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/background_speech_bubble.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#98 [mod] 마이페이지 디자인 수정
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_default_profile.xml
  app/src/main/res/drawable/ic_my_page_default_profile.xml
  app/src/main/res/layout/activity_my_bookmarks.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_my_review_detail.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#101 [feat] 마이페이지 뷰 말풍선 구현
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/background_left_speech_bubble.xml
  app/src/main/res/drawable/background_right_speech_bubble.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/view_speech_bubble.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#100 [mod] 필터뷰 수정
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseFilter.kt
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/FilterInfoType.kt
  app/src/main/res/drawable/background_enabled_3_division_filter_option.xml
  app/src/main/res/drawable/background_enabled_4_division_filter_option.xml
  app/src/main/res/drawable/ic_filter_arrow_right.xml
  app/src/main/res/drawable/selector_item_filter_text.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_bread_type_filter.xml
  app/src/main/res/layout/fragment_main_purpose_filter.xml
  app/src/main/res/layout/fragment_nutrient_type_filter.xml
  app/src/main/res/menu/bnv_menu.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮
