Repository GEON-PPANG/GEON-PPANG-AOS, pull requests merged in 2023-07, with the labels that each got.

#8 [feat] 바텀 네비게이션 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/res/drawable/background_bottom_navigation.xml
  app/src/main/res/drawable/bottom_navigation_top_shadow.xml
  app/src/main/res/drawable/ic_bnv_home_selected.xml
  app/src/main/res/drawable/ic_bnv_home_unselected.xml
  app/src/main/res/drawable/ic_bnv_mypage_selected.xml
  app/src/main/res/drawable/ic_bnv_mypage_unselected.xml
  app/src/main/res/drawable/ic_bnv_storelist_selected.xml
  app/src/main/res/drawable/ic_bnv_storelist_unselected.xml
  app/src/main/res/drawable/menu_selector_color.xml
  app/src/main/res/drawable/selector_menu_home_icon.xml
  app/src/main/res/drawable/selector_menu_mypage_icon.xml
  app/src/main/res/drawable/selector_menu_storelist_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bnv_menu.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#13 [mod] dimens 추가 및 chip style 수정 및 구현
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#17 [feat] 마이페이지 뷰 구현
  app/src/main/java/com/sopt/geonppang/domain/model/BreadType.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Profile.kt
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/background_my_page_buttons.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_my_page_bookmark.xml
  app/src/main/res/drawable/ic_my_page_default_profile.xml
  app/src/main/res/drawable/ic_my_page_review.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#6 [feat] 홈 뷰 구현
  app/src/main/java/com/sopt/geonppang/domain/model/BestBakery.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BestReview.kt
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/background_home_bakery_box.xml
  app/src/main/res/drawable/background_search_box.xml
  app/src/main/res/drawable/bread1.png
  app/src/main/res/drawable/foreground_shadow.xml
  app/src/main/res/drawable/ic_bookmark_selected.xml
  app/src/main/res/drawable/ic_bookmark_unselected.xml
  app/src/main/res/drawable/ic_gmo_mark.xml
  app/src/main/res/drawable/ic_haccp_mark.png
  app/src/main/res/drawable/ic_home_filter.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_vegan_mark.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#14 [feat] 검색뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/domain/model/Bakery.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BreadType.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/extension/ContextExt.kt
  app/src/main/res/drawable/background_search_box.xml
  app/src/main/res/drawable/bbang1.png
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/img_search_empty.xml
  app/src/main/res/drawable/img_search_init.xml
  app/src/main/res/drawable/shape_border_radius_5.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#24 [feat] 마이 페이지 저장 목록 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyStoreListActivity.kt
  app/src/main/res/drawable/ic_empty_store_list.xml
  app/src/main/res/layout/activity_my_store_list.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#27 [feat] 마이페이지 내 리뷰 모아보기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/domain/model/Review.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewAdapter.kt
  app/src/main/res/drawable/ic_empty_my_review.xml
  app/src/main/res/drawable/ic_my_review_more.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#23 [feat] 상세페이지 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/domain/model/BakeryInfo.kt
  app/src/main/java/com/sopt/geonppang/domain/model/DetailReview.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Menu.kt
  app/src/main/java/com/sopt/geonppang/domain/model/MyReview.kt
  app/src/main/java/com/sopt/geonppang/domain/model/ReviewData.kt
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailMenuAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailNoReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewDataAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/util/ChipFactory.kt
  app/src/main/java/com/sopt/geonppang/util/CustomSnackbar.kt
  app/src/main/java/com/sopt/geonppang/util/VerticalProgressBar.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingAdapter.kt
  app/src/main/res/drawable/background_detail_bottom_app_bar_review_create.xml
  app/src/main/res/drawable/background_detail_menu_notice.xml
  app/src/main/res/drawable/background_detail_progress_bar_background.xml
  app/src/main/res/drawable/background_detail_progress_bar_progress.xml
  app/src/main/res/drawable/background_detail_review.xml
  app/src/main/res/drawable/background_snackbar.xml
  app/src/main/res/drawable/bakery.png
  app/src/main/res/drawable/detail_page_bottom_app_bar_shadow.xml
  app/src/main/res/drawable/ic_call.xml
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_detail_logo_profile.xml
  app/src/main/res/drawable/ic_link.xml
  app/src/main/res/drawable/ic_map.xml
  app/src/main/res/drawable/ic_no_review.xml
  app/src/main/res/drawable/ic_nongmo_mark.xml
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_store.xml
  app/src/main/res/drawable/ic_time.xml
  app/src/main/res/drawable/ic_white_logo.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_detail_menu.xml
  app/src/main/res/layout/item_detail_no_review.xml
  app/src/main/res/layout/item_detail_review.xml
  app/src/main/res/layout/item_detail_review_graph.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/view_chip_review.xml
  app/src/main/res/layout/view_snackbar.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#22 [feat] 리뷰 쓰기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewCancelBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/KeyWordType.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/LikeType.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingAdapter.kt
  app/src/main/res/color/enable_review_writing_chip_color.xml
  app/src/main/res/color/enable_review_writing_color.xml
  app/src/main/res/color/selector_bread_sort_color.xml
  app/src/main/res/drawable/background_review_bottom_btn.xml
  app/src/main/res/drawable/background_review_bottom_content.xml
  app/src/main/res/drawable/background_review_box.xml
  app/src/main/res/drawable/background_review_enable_status.xml
  app/src/main/res/drawable/background_review_error_box.xml
  app/src/main/res/drawable/background_review_need_change_status.xml
  app/src/main/res/drawable/ic_gmo_mark.xml
  app/src/main/res/drawable/ic_haccp_mark.png
  app/src/main/res/drawable/ic_vegan_mark.xml
  app/src/main/res/drawable/img_review_writing_cancel.png
  app/src/main/res/drawable/img_review_writing_success.png
  app/src/main/res/drawable/review_page_bottom_app_bar_shadow.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_bottom_review_writing_cancel.xml
  app/src/main/res/layout/dialog_bottom_review_writing_success.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 😽 주영 😽, 💫 feat 💫

#10 [feat] 필터 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/domain/model/Filter.kt
  app/src/main/java/com/sopt/geonppang/domain/model/NutrientFilter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/BreadTypeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterViewPagerAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/NutrientTypeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/BreadFilterType.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/MainPurposeType.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/NutrientFilterType.kt
  app/src/main/res/color/selector_filter_button_color.xml
  app/src/main/res/drawable/background_disabled_3_division_filter_option.xml
  app/src/main/res/drawable/background_disabled_4_division_filter_option.xml
  app/src/main/res/drawable/background_enabled_3_division_filter_option.xml
  app/src/main/res/drawable/background_enabled_4_division_filter_option.xml
  app/src/main/res/drawable/ic_welcome.xml
  app/src/main/res/drawable/selector_filter_button_text.xml
  app/src/main/res/drawable/selector_item_3_division_filter_button.xml
  app/src/main/res/drawable/selector_item_4_division_filter_button.xml
  app/src/main/res/drawable/selector_item_filter_text.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_bread_type_filter.xml
  app/src/main/res/layout/fragment_main_purpose_filter.xml
  app/src/main/res/layout/fragment_nutrient_type_filter.xml
  app/src/main/res/layout/item_bread_type_filter_button.xml
  app/src/main/res/layout/item_nutrient_type_filter_button.xml
  app/src/main/res/layout/view_bread_type_button.xml
  app/src/main/res/layout/view_main_purpose_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#31 [feat] 전체 뷰 연결
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyStoreListActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#33 [init] 서버 통신 기초 세팅
  app/build.gradle
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/geonppang/di/NetworkModule.kt
Labels: 🐰 다은 🐰, 🍀 init 🍀

#39 [feat] 검색뷰 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/SearchDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBestBakery.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBestReview.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseSearch.kt
  app/src/main/java/com/sopt/geonppang/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/HomeService.kt
  app/src/main/java/com/sopt/geonppang/data/service/SearchService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Bakery.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/SearchRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_bookmark_small.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_bread_type_filter_button.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/item_nutrient_type_filter_button.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#46 [feat] 마이페이지 리뷰 모아보기 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/MypageReviewDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseMypageReview.kt
  app/src/main/java/com/sopt/geonppang/data/repository/MypageReviewRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/MypageReviewService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Bakery.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/MypageReviewRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewActivity.kt
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/item_my_review.xml
Labels: 😽 주영 😽, 💫 feat 💫

#43 [feat] 상세페이지 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/DetailDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestBookMark.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBookMark.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseDetailBakery.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseDetailReview.kt
  app/src/main/java/com/sopt/geonppang/data/repository/DetailRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/DetailService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BakeryInfo.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BookMark.kt
  app/src/main/java/com/sopt/geonppang/domain/model/DetailReview.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Menu.kt
  app/src/main/java/com/sopt/geonppang/domain/model/ReviewData.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/DetailRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryRecyclerViewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailMenuAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyReviewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyStoreListActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/util/CustomSnackbar.kt
  app/src/main/res/drawable/background_detail_menu_notice.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_bookmark_selected.xml
  app/src/main/res/drawable/ic_bookmark_unselected.xml
  app/src/main/res/drawable/ic_review.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_detail_review_graph.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#50 [feat] 리뷰 작성하기 api 연동
  app/build.gradle
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/ReviewWritingDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestReviewWriting.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseReviewWriting.kt
  app/src/main/java/com/sopt/geonppang/data/repository/ReviewWritingWritingRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/ReviewWritingService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/ReviewWritingRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/model/BakeryReviewWritingInfo.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyStoreListActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewCancelBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/KeyWordType.kt
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 😽 주영 😽, 💫 feat 💫

#54 [mod] 이미지 뷰 radius 적용 안되는 이슈 해결
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#56 [mod] 홈 <-> 디테일 뷰 화면 전환 구현
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/item_home_best_bakery.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#51 [feat] 필터뷰 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/FilterDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestFilter.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseFilter.kt
  app/src/main/java/com/sopt/geonppang/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/FilterService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/SelectedFilter.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/FilterRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/FilterInfoType.kt
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/dialog_bottom_signup_email.xml
  app/src/main/res/layout/dialog_bottom_signup_nickname.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#59 [feat] 회원가입 닉네임 sharedpreference
  app/src/main/java/com/sopt/geonppang/data/datasource/local/GPDataStore.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseBestReview.kt
  app/src/main/java/com/sopt/geonppang/domain/model/BestReview.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpEmailBottomSheetDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpNicknameBottomSheetDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpViewModel.kt
  app/src/main/res/layout/activity_signup_email.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_main_purpose_filter.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 😽 주영 😽, 💫 feat 💫

#58 [mod] 각종 이슈 해결 (마이페이지 스크롤뷰, 버튼 ripple 제거, 상세페이지 이미지 문제 해결)
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#61 [feat] QA 반영
  app/src/main/java/com/sopt/geonppang/domain/model/BestBakery.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryRecyclerViewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingAdapter.kt
  app/src/main/res/color/selector_bread_lost_filter_background.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/view_main_purpose_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 🐸 지현 🐸, 😽 주영 😽, 💫 feat 💫

#63 [mod] 불필요한 파일 삭제 및 전체 레이아웃 수정
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/DummyDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestDummy.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseDummy.kt
  app/src/main/java/com/sopt/geonppang/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/DummyService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/DummyData.kt
  app/src/main/java/com/sopt/geonppang/domain/model/Filter.kt
  app/src/main/java/com/sopt/geonppang/domain/model/NutrientFilter.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/DummyRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/common/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/dummy/DummyActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/dummy/DummyViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyStoreListActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/review/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpPasswordActivity.kt
  app/src/main/res/drawable/bakery.png
  app/src/main/res/drawable/bbang1.png
  app/src/main/res/drawable/bread1.png
  app/src/main/res/layout/activity_dummy.xml
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_my_store_list.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/activity_signup_password.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 🐸 지현 🐸, 🔮mod 🔮
