Repository GEON-PPANG/GEON-PPANG-AOS, pull requests merged in 2023-09, with the labels that each got.

#110 [feat] 신고하기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/signup/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/type/ReportCategoryType.kt
  app/src/main/res/drawable/background_report_box.xml
  app/src/main/res/drawable/ic_big_smile.xml
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/dialog_bottom_report_success.xml
  app/src/main/res/layout/item_detail_review.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#106 [feat] 상세페이지 웹 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/presentation/common/WebViewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/res/layout/activity_web_view.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#112 [mod] 필터뷰 뒤로가기 설정
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/FilterActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filter/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
Labels: 🐸 지현 🐸, 🔮mod 🔮

#114 [feat] 마이페이지 웹 연결
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#102 [mod] 리뷰 작성 뷰 디자인 수정 사항 반영 및 로직 변경
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewCancelBottomDialogFragment.kt
  app/src/main/res/color/enable_review_writing_chip_color.xml
  app/src/main/res/color/selector_bread_sort_color.xml
  app/src/main/res/drawable/ic_review_bread.xml
  app/src/main/res/drawable/ic_smile_review_view.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/dialog_bottom_review_writing_cancel.xml
  app/src/main/res/layout/dialog_bottom_review_writing_success.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: 😽 주영 😽, 🔮mod 🔮

#105 [refactor] 리팩토링
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/FilterDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/FilterSettingDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestSettingFilter.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseSettingFilter.kt
  app/src/main/java/com/sopt/geonppang/data/repository/FilterRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/repository/FilterSettingRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/FilterService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/FilterSettingRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameBottomSheetDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListSortBottomSheetDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/common/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/BreadTypeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterViewPagerAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/NutrientTypeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myReviewDetail/MyReviewDetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/LogoutDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/WithdrawDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewCancelBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/util/binding/BindingDialogFragment.kt
  app/src/main/res/layout/activity_filter.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/activity_signup_nickname.xml
  app/src/main/res/layout/activity_welcome.xml
  app/src/main/res/layout/dialog_bottom_signup_nickname_fail.xml
  app/src/main/res/layout/dialog_bottom_signup_nickname_success.xml
  app/src/main/res/layout/dialog_middle.xml
  app/src/main/res/layout/fragment_bread_type_filter.xml
  app/src/main/res/layout/fragment_main_purpose_filter.xml
  app/src/main/res/layout/fragment_nutrient_type_filter.xml
Labels: 🐰 다은 🐰, 💖refactor💖

#117 [feat] 리뷰 신고 뷰 api 연결
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/ReportDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestReport.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseReport.kt
  app/src/main/java/com/sopt/geonppang/data/repository/ReportRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/ReportService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/model/ReviewReport.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/ReportRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportViewModel.kt
  app/src/main/res/layout/item_detail_review.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#119 [feat] 로그아웃, 회원탈퇴 api 연결
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseLogout.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseWithdraw.kt
  app/src/main/java/com/sopt/geonppang/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/AuthService.kt
  app/src/main/java/com/sopt/geonppang/di/RepositoryModule.kt
  app/src/main/java/com/sopt/geonppang/di/ServiceModule.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/LogoutDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/mypage/WithdrawDialog.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#125 [mod] 저당무설탕 -> 대체당 변경, 다이얼로그 배경색 수정
  app/src/main/java/com/sopt/geonppang/util/binding/BindingDialogFragment.kt
  app/src/main/res/layout/activity_my_review.xml
  app/src/main/res/layout/activity_my_review_detail.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/layout/view_bread_type_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#127 [feat] 상세페이지 지도 웹 연결
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#132 [init] amplitude 기초 세팅
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/App.kt
  app/src/main/java/com/sopt/geonppang/util/AmplitudeUtils.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#129 [feat] 건빵집 리스트 말풍선 구현
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#124 [mod] 리뷰 작성 뷰 에러 수정 및 flow migration
  app/build.gradle
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingViewModel.kt
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 🐰 다은 🐰, 🔮mod 🔮

#120 [feat] 카카오 로그인 구현
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestSignup.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseSignup.kt
  app/src/main/java/com/sopt/geonppang/data/service/AuthService.kt
  app/src/main/java/com/sopt/geonppang/data/service/KakaoAuthService.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/item_home_best_review.xml
  gradlew
  settings.gradle
Labels: 😽 주영 😽, 💫 feat 💫

#134 [feat] 홈 뷰 엠플리튜드 이벤트 코드 및 특정 뷰 -> 필터링 이탈, 완료율 이벤트 코드를 심기
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#138 [feat] 마이페이지 엠플리튜드 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/presentation/mypage/MyPageFragment.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#136 [feat] 건빵집 리스트에 엠플리튜드 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListSortBottomSheetDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/AmplitudeUtils.kt
  app/src/main/res/layout/dialog_bottom_bakery_list_sort.xml
  app/src/main/res/layout/fragment_bakery_list.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#152 [mod] 홈뷰-베스트리뷰에 리뷰 텍스트에 앞뒤 쌍따옴표(") 붙이기
  app/src/main/java/com/sopt/geonppang/presentation/MainActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyPageFragment.kt
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#154 [feat] 자체 회원가입 api 연동 및 회원가입 로직 구현
  app/src/main/java/com/sopt/geonppang/data/datasource/local/GPDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestNicknameSetting.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseNickNameSetting.kt
  app/src/main/java/com/sopt/geonppang/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/AuthService.kt
  app/src/main/java/com/sopt/geonppang/data/service/KakaoAuthService.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/res/drawable/shape_sign_kakao_btn.xml
  app/src/main/res/layout/activity_sign.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#150 [mod] 검색 완료 이벤트 트래킹 시점 서버통신 성공일때로 수정
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
Labels: 🐰 다은 🐰, 🔮mod 🔮

#159 [feat] 베이커리 이미지 로딩 뷰 구현
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/common/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/util/extension/ContextExt.kt
  app/src/main/res/drawable/img_bakery_image_loading.xml
  app/src/main/res/drawable/img_bakery_image_loading_best_bakery.xml
  app/src/main/res/drawable/img_bakery_image_loading_best_review.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/item_my_review.xml
Labels: 🐰 다은 🐰, 💫 feat 💫

#161 [feat] 회원탈퇴, 로그아웃 로직 구현 및 local DB 삭제
  app/src/main/java/com/sopt/geonppang/data/service/KakaoAuthService.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/LogoutDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/WithdrawDialog.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#145 [mod] 상세페이지 이슈 해결
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/activity_detail.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#144 [feat] 상세페이지 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailBakeryInfoAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyBookMarksActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyReviewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#163 [feat] 리뷰 신고뷰 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/AmplitudeUtils.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#157 [feat] 토큰 재발급 로직 구현(토큰 재발급 실패시 SignActivity 이동
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#164 [feat] 리뷰 작성뷰 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/presentation/model/AmplitudeReviewWritingInfo.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewCancelBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingViewModel.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#146 [feat] 자체 로그인 api 연동
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/model/request/RequestLogin.kt
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseLogin.kt
  app/src/main/java/com/sopt/geonppang/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/AuthService.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LogInViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginFailBottomDialogFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_signup_nickname.xml
  app/src/main/res/layout/dialog_bottom_login_fail.xml
Labels: 😽 주영 😽, 💫 feat 💫

#168 [fix] 인터셉터에서 재발급 실패시 startActivity를 호출할때 발생하는 ANR 오류 해결
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
Labels: 🐰 다은 🐰, 🔨 fix 🔨

#171 [mod] 자동 로그인, 로그인 로직 수정
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LogInViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginActivity.kt
Labels: 🐰 다은 🐰, 🔮mod 🔮

#175 [mod] 자체 회원가입 후 로그인 페이지로 이동하도록 수정
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginActivity.kt
Labels: 🐰 다은 🐰, 🔮mod 🔮

#174 [feat] 카카오 회원가입 시 응답 헤더값 자체 디비에 저장
  app/src/main/java/com/sopt/geonppang/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/com/sopt/geonppang/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/geonppang/data/service/AuthService.kt
  app/src/main/java/com/sopt/geonppang/domain/repository/AuthRepository.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#179 [fix] 토큰 재발급 후 api header에 리프레시 토큰이 추가되어 다시 재발급 되는 에러 해결
  app/src/main/java/com/sopt/geonppang/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
Labels: 🐰 다은 🐰, 🔨 fix 🔨

#177 [feat] General 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/App.kt
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LoginActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/LogoutDialog.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/WithdrawDialog.kt
Labels: 🐸 지현 🐸, 💫 feat 💫

#183 [feat] 상세페이지 전화번호 없는 경우에 대한 로직 구현
  app/src/main/res/layout/item_detail_bakery_info.xml
Labels: 🐸 지현 🐸, 💫 feat 💫

#182 [fix] 소셜 로그인, 회원가입 후 뒤로가기를 누를때 생기는 버벅임 문제 해결
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingViewModel.kt
Labels: 🐰 다은 🐰, 🔨 fix 🔨

#185 [mod] 홈 뷰 footer background 색상 수정
  app/src/main/res/layout/fragment_home.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#187 [fix] 닉네임 중복확인 오류 확인 후 수정
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/res/layout/activity_signup_nickname.xml
Labels: 😽 주영 😽, 🔨 fix 🔨

#193 [fix] 토큰 재발급시 발생하는 에러 해결
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyBookMarksActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyPageViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyReviewActivity.kt
  app/src/main/res/layout/fragment_bakery_list.xml
Labels: 🐰 다은 🐰, 🔨 fix 🔨

#191 [mod] QA 반영
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/res/layout/activity_report.xml
  app/src/main/res/layout/fragment_bread_type_filter.xml
  app/src/main/res/layout/fragment_main_purpose_filter.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_nutrient_type_filter.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_detail_review.xml
  app/src/main/res/layout/view_speech_bubble.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#194 [mod] qa 반영
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyBookMarksActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyReviewActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/search/SearchActivity.kt
  app/src/main/java/com/sopt/geonppang/util/CustomItemDecoration.kt
  app/src/main/res/color/selector_bread_sort_color.xml
  app/src/main/res/drawable/shape_border_top_radius_5.xml
  app/src/main/res/layout/activity_my_bookmarks.xml
  app/src/main/res/layout/activity_my_review_detail.xml
  app/src/main/res/layout/fragment_bakery_list.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_home_best_review.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#195 [mod] qa 반영
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/res/drawable/ic_bnv_home_selected.xml
  app/src/main/res/drawable/ic_haccp_mark.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_review_writing.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/activity_signup_nickname.xml
  app/src/main/res/layout/item_bakery.xml
  app/src/main/res/layout/item_detail_bakery_info.xml
  app/src/main/res/layout/item_home_best_bakery.xml
  app/src/main/res/layout/item_my_review.xml
  app/src/main/res/mipmap-hdpi/ic_haccp_mark_26.png
  app/src/main/res/mipmap-mdpi/ic_haccp_mark_26.png
  app/src/main/res/mipmap-xhdpi/ic_haccp_mark_26.png
  app/src/main/res/mipmap-xxhdpi/ic_haccp_mark_26.png
  app/src/main/res/mipmap-xxxhdpi/ic_haccp_mark_26.png
  app/src/main/res/values/strings.xml
Labels: 😽 주영 😽, 🔮mod 🔮

#200 [fix] multiple touch
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/common/BakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestBakeryAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/BestReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyReviewAdapter.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewSuccessBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/util/extension/ViewExt.kt
Labels: 🐰 다은 🐰, 🔨 fix 🔨

#197 [mod] 2차 QA 반영
  app/src/main/java/com/sopt/geonppang/presentation/detail/DetailActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewCancelBottomDialogFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingActivity.kt
  app/src/main/java/com/sopt/geonppang/util/CustomSnackbar.kt
  app/src/main/res/layout/view_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: 🐸 지현 🐸, 🔮mod 🔮

#201 [feat] 온보딩 엠플리튜드 트래킹 이벤트 코드 심기
  app/src/main/java/com/sopt/geonppang/data/datasource/local/GPDataSource.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/MainPurposeFilterFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/model/AmplitudeFilterSettingInfo.kt
Labels: 😽 주영 😽, 💫 feat 💫

#204 [mod] 2차 QA 반영
  app/src/main/res/layout/activity_signup.xml
Labels: 😽 주영 😽, 🔮mod 🔮

#205 [mod] 말풍선, 닉네임, 주목적 칩 등의 초기값 수정
  app/src/main/java/com/sopt/geonppang/presentation/bakeryList/BakeryListViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/home/HomeViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyPageFragment.kt
  app/src/main/java/com/sopt/geonppang/presentation/myPage/MyPageViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_bottom_review_writing_cancel.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#208 [mod] amplitude event를 전체적으로 수정
  app/build.gradle
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/WelcomeActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/MainPurposeFilterFragment.kt
  app/src/main/res/layout/activity_signup_nickname.xml
Labels: 🐰 다은 🐰, 🔮mod 🔮

#210 [mod] 로그인 amplitude 수정
  app/src/main/java/com/sopt/geonppang/presentation/SplashActivity.kt
Labels: 🐸 지현 🐸, 🔮mod 🔮

#211 [feat] amplitude user property setting
  app/src/main/java/com/sopt/geonppang/data/model/response/ResponseSignup.kt
  app/src/main/java/com/sopt/geonppang/domain/model/SignUpInfo.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/AuthViewModel.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/util/AmplitudeUtils.kt
Labels: 🐰 다은 🐰, 💫 feat 💫

#215 [mod] 엠플리튜드 이벤트 로그 찍히는 시점 분리
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/filterSetting/FilterSettingActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/report/ReportActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/reviewWriting/ReviewWritingActivity.kt
Labels: 🐰 다은 🐰, 🔮mod 🔮

#213 [feat] 릴리즈 준비
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/java/com/sopt/geonppang/presentation/auth/SignUpNicknameActivity.kt
  app/src/main/java/com/sopt/geonppang/presentation/login/LogInViewModel.kt
  app/src/main/java/com/sopt/geonppang/util/extension/ContextExt.kt
  app/src/main/java/com/sopt/geonppang/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_login.xml
Labels: 🐰 다은 🐰, 💫 feat 💫
